[config]
mode = "dark"

[templates.alacritty]
input_path = "~/.config/matugen/templates/alacritty.toml"
output_path = "~/.cache/matugen/alacritty.toml"

[templates.neovim]
input_path = "~/.config/matugen/templates/nvim.lua"
output_path = '~/.cache/matugen/generated.lua'
