[config]
mode = "dark"

[templates.alacritty]
input_path = "~/.config/matugen/templates/alacritty.toml"
output_path = "~/.cache/matugen/alacritty.toml"

[templates.neovim]
input_path = "~/.config/matugen/templates/nvim.lua"
output_path = '~/.cache/matugen/generated.lua'

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.cache/matugen/rofi.rasi"

[templates.spicetify]
input_path = "~/.config/matugen/templates/spicetify.ini"
output_path = "~/.config/spicetify/Themes/matugen/color.ini"
post_hook = "spicetify apply"

