[config]
mode = "dark"

[templates.alacritty]
input_path = "~/.config/matugen/templates/alacritty.toml"
output_path = "~/.cache/matugen/alacritty.toml"

[templates.neovim]
input_path = "~/.config/matugen/templates/nvim.lua"
output_path = '~/.cache/matugen/generated.lua'

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.cache/matugen/rofi.rasi"

[templates.spicetify]
input_path = "~/.config/matugen/templates/spicetify.ini"
output_path = "~/.config/spicetify/Themes/matugen/color.ini"

[templates.vscode]
input_path = "~/.config/matugen/templates/vscode.json"
output_path = "~/.cache/matugen/vscode.json"
post_hook = "jq -s '.[0] * .[1]' ~/.config/Code/User/settings.json ~/.cache/matugen/vscode.json > temp.json && mv temp.json ~/.config/Code/User/settings.json"

[templates.obsidian]
input_path = "~/.config/matugen/templates/obsidian.css"
output_path = "~/Obsidian/.obsidian/snippets/obsidian.css"

[templates.zathura]
input_path = "~/.config/matugen/templates/zathurarc"
output_path = "~/.config/zathura/zathurarc"

[templates.dunst]
input_path = "~/.config/matugen/templates/dunstrc"
output_path = "~/.config/dunst/dunstrc"
