[cursor]
thickness = 0.2

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 8

[font.normal]
family = "FiraCode Nerd Font"

[window]
opacity = 0.8

[window.padding]
x = 10
y = 10

[general]
import = ["~/.cache/matugen/alacritty.toml"]


