-- Auto-generated by Matugen
-- Only override UI colors, NOT syntax colors (those come from gruvbox)

local function set_hl_multiple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Background and surface colors
vim.api.nvim_set_hl(0, 'Normal',       { bg = '{{colors.background.default.hex}}' })
vim.api.nvim_set_hl(0, 'NormalNC',     { bg = '{{colors.surface_container_lowest.default.hex}}' })
vim.api.nvim_set_hl(0, 'NormalFloat',  { bg = '{{colors.surface_container_low.default.hex}}' })
vim.api.nvim_set_hl(0, 'FloatBorder',  { bg = '{{colors.surface_container_low.default.hex}}' })
vim.api.nvim_set_hl(0, 'SignColumn',   { bg = '{{colors.background.default.hex}}' })
vim.api.nvim_set_hl(0, 'LineNr',       { bg = '{{colors.background.default.hex}}' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { bg = '{{colors.surface_container_low.default.hex}}' })
vim.api.nvim_set_hl(0, 'CursorLine',   { bg = '{{colors.surface_container_low.default.hex}}' })
vim.api.nvim_set_hl(0, 'ColorColumn',  { bg = '{{colors.surface_container_lowest.default.hex}}' })
vim.api.nvim_set_hl(0, 'Folded',       { bg = '{{colors.surface_container_low.default.hex}}' })

-- Popups / menus
vim.api.nvim_set_hl(0, 'Pmenu',        { bg = '{{colors.surface_container_low.default.hex}}' })
vim.api.nvim_set_hl(0, 'PmenuSel',     { bg = '{{colors.primary_container.default.hex}}', fg = '{{colors.background.default.hex}}' })
vim.api.nvim_set_hl(0, 'PmenuSbar',    { bg = '{{colors.surface_container_lowest.default.hex}}' })
vim.api.nvim_set_hl(0, 'PmenuThumb',   { bg = '{{colors.outline_variant.default.hex}}' })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '{{colors.primary_container.default.hex}}',
  fg = '{{colors.background.default.hex}}',
})

-- Comments (matugen-tinted but kept readable)
set_hl_multiple({ 'Comment', '@comment' }, {
  fg = '{{colors.on_tertiary_container.default.hex}}',
  italic = true,
})

-- Statusline
vim.api.nvim_set_hl(0, 'StatusLine',   { bg = '{{colors.surface_container_lowest.default.hex}}', fg = '{{colors.primary.default.hex}}' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { bg = '{{colors.surface_container_lowest.default.hex}}', fg = '{{colors.outline_variant.default.hex}}' })
vim.api.nvim_set_hl(0, 'MsgArea',      { bg = '{{colors.surface_container_lowest.default.hex}}', fg = '{{colors.primary.default.hex}}' })

-- Telescope / fzf borders (if used)
vim.api.nvim_set_hl(0, 'TelescopeNormal',        { bg = '{{colors.surface_container_lowest.default.hex}}' })
vim.api.nvim_set_hl(0, 'TelescopeBorder',        { bg = '{{colors.surface_container_lowest.default.hex}}', fg = '{{colors.outline_variant.default.hex}}' })
vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret',{ fg = '{{colors.primary.default.hex}}' })
