backend = "glx"
vsync = true

fading = true;
fade-in-step = 0.1
fade-out-step = 0.1

# General animation settings
animation-stiffness = 600;  # Increased for faster animations
animation-dampening = 15;   # Decreased for less smoothing
animation-clamping = true;
animation-mass = 0.5;       # Added: Lower mass for quicker movement

# FT-Labs
animations = true
animation-stiffness-in-tag = 300.0
animation-stiffness-tag-change = 90.0;
animation-for-open-window = "slide-up"
animation-for-unmap-window = "squeeze-bottom" # Weirdly this makes switching workspaces look nice
animation-for-transient-window = "none" #popup windows

# Shadow
shadow = true;
shadow-offset-x = -12
shadow-offset-y = -10
shadow-radius = 12
shadow-opacity = 1

blur-method = "dual_kawase"
blur-strength = 8

blur-background-exclude = [
    "class_g = 'slop'"
];

active-opacity = 1
# inactive-opacity = 0.8


opacity-rule = [ 
    "100:class_g = 'rofi'"
];

opacity-rule = [
  "85:class_g = 'Spotify'"
];

opacity-rule = [
  "100:class_g = 'Zathura'"
];


# Performance Improvments:
glx-no-stencil = true
xrender-sync-fence = true

corner-radius = 10
