#!/usr/bin/env sh

set -x
exec > ~/.config/bspwm/bspwm.log 2>&1

# kill all startup programs
killall -q sxhkd picom polybar dunst greenclip 

# application startup
sxhkd & # & makes it work async
picom -b &
dunst &
greenclip daemon &

"$HOME/.config/polybar/launch.sh" 

### ===============================
### Environment
### ===============================

# Wallpapers
WALL_CACHE="$HOME/.cache/matugen/current_wallpaper"

[ -f "$WALL_CACHE" ] && setwall "$(cat "$WALL_CACHE")"


# ===============================
# Colors from xrdb (matugen / pywal compatible)
# ===============================

# Wallpapers
WALL_CACHE="$HOME/.cache/matugen/current_wallpaper"
[ -f "$WALL_CACHE" ] && setwall "$(cat "$WALL_CACHE")"

# Load matugen colors
[ -f "$HOME/.cache/matugen/colors.sh" ] && . "$HOME/.cache/matugen/colors.sh"


### ===============================
### Monitors & Desktops
### ===============================

bspc monitor $(bspc query -M --names | head -n 1) -d 1 2 3 4 5

### ===============================
### BSPWM Configuration
### ===============================

bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

# Dynamic colors
bspc config normal_border_color  "$color0"
bspc config focused_border_color "$color2"

### ===============================
### Rules
### ===============================

bspc rule -a iwgtk state=floating
bspc rule -a Explorer state=floating
bspc rule -a Spotify state=floating
bspc rule -a Obsidian state=floating



