#!/usr/bin/env sh

# kill all startup programs
killall -q sxhkd picom polybar dunst greenclip 

# application startup
sxhkd & # & makes it work async
picom -b &
dunst &
greenclip daemon &

"$HOME/.config/polybar/launch.sh"

### ===============================
### Environment
### ===============================

# Wallpapers
WALL_CACHE="$HOME/.cache/matugen/current_wallpaper"

[ -f "$WALL_CACHE" ] && setwall "$(cat "$WALL_CACHE")"


# ===============================
# Colors from xrdb (matugen / pywal compatible)
# ===============================

get_xrdb() {
  xrdb -query | awk -F: "/\\*$1/ {print \$2}" | tr -d '[:space:]'
}

color0="$(get_xrdb color0)"
color1="$(get_xrdb color1)"
color4="$(get_xrdb color4)"


### ===============================
### Monitors & Desktops
### ===============================

bspc monitor primary -d 1 2 3 4 5

### ===============================
### BSPWM Configuration
### ===============================

bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

# Dynamic colors
bspc config normal_border_color  "$color1"
bspc config focused_border_color "$color4"

### ===============================
### Rules
### ===============================

bspc rule -a iwgtk state=floating
bspc rule -a Explorer state=floating



