; ==================================================
; Pywal colors (via xrdb)
; ==================================================
[colors]
background = ${xrdb:background:#111113}
foreground = ${xrdb:foreground:#c3c3c4}

black       = ${xrdb:color0:#111113}
darkred     = ${xrdb:color1:#A3987D}
darkgreen   = ${xrdb:color2:#A89D82}
darkyellow  = ${xrdb:color3:#B6A98A}
darkblue    = ${xrdb:color4:#C8B997}
darkmagenta = ${xrdb:color5:#D1C29E}
darkcyan    = ${xrdb:color6:#D9CAA5}
grey        = ${xrdb:color7:#c3c3c4}

lightgrey   = ${xrdb:color8:#5a5a6e}
red         = ${xrdb:color9:#A3987D}
green       = ${xrdb:color10:#A89D82}
yellow      = ${xrdb:color11:#B6A98A}
blue        = ${xrdb:color12:#C8B997}
magenta     = ${xrdb:color13:#D1C29E}
cyan        = ${xrdb:color14:#D9CAA5}
white       = ${xrdb:color15:#c3c3c4}

; ==================================================
; Base Bar
; ==================================================
[bar/base]
height = 30px
radius = 8
fixed-center = true
wm-restack = bspwm
enable-ipc = true

offset-y = 10
line-size = 0
border-size = 2
border-color = ${colors.darkblue}


padding-left = 0
padding-right = 0

background = ${colors.background}
foreground = ${colors.foreground}

font-0 = "FiraCode Nerd Font:size=11;2"

; ==================================================
; Bars
; ==================================================

[bar/left_one]
inherit = bar/base
offset-x = 10
width = 10%
modules-center = bspwm

[bar/left_two]
inherit = bar/base
offset-x = 11%
offset-y = 11
height = 29px
width = 20%
modules-center = spotify

[bar/middle]
inherit = bar/base
offset-x = 35%
offset-y = 12
width = 30%
height = 27
modules-center = title

[bar/right_two]
inherit = bar/base
offset-x = 69%
width = 15%
modules-center = network bluetooth-headphones bluetooth-keyboard keyboard mouse webcam

[bar/right_one]
inherit = bar/base
height = 28px
offset-x = 84.5%
width = 15%
modules-center = battery date

; ==================================================
; Modules
; ==================================================

[module/title]
type = custom/script
exec = ~/.config/polybar/scripts/scroll_window_title.sh
tail = true
label = %output%
label-padding = 1
label-empty = Welcome To Reclude

; ---------------- Battery ----------------
[module/battery]
type = internal/battery
battery = BAT1
adapter = AC
poll-interval = 5

full-at = 100
low-at = 10

format-discharging = <label-discharging>
label-discharging = "󰁹 %percentage_raw%%  "

format-charging = <label-charging>
label-charging = "󰂄 %percentage_raw%%  "

format-low = <label-low>
label-low = "󰂃 %percentage_raw%%  "

format-full = <label-full>
label-full = "󱈑 %percentage_raw%%  "

; ---------------- BSPWM ----------------
[module/bspwm]
type = internal/bspwm
format-padding = 1

label-focused = 󰮯
label-occupied = 󰊠
label-empty = 

label-focused-foreground = ${colors.blue}
label-occupied-foreground = ${colors.foreground}
label-empty-foreground = ${colors.lightgrey}

label-focused-padding = 1
label-occupied-padding = 1
label-empty-padding = 1

; ---------------- Date ----------------
[module/date]
type = internal/date
interval = 1.0
date = "%d/%m"
time = "%H:%M"
label = "󰃭 %date%   %time%"

; ---------------- Network ----------------
[module/network]
type = internal/network
interface = wlan0
interface-type = wireless
interval = 3.0
unknown-as-up = true

label-connected = "󰖩 "
label-disconnected = "󱚼 "

; ---------------- Bluetooth Headphones ----------------
[module/bluetooth-headphones]
type = custom/script
exec = bluetoothctl info EB:06:EF:65:42:AB | grep -q "Connected: yes" && echo " "
exec-if = bluetoothctl info EB:06:EF:65:42:AB | grep -q "Connected: yes"
interval = 2
format-prefix = 
format-prefix-foreground = ${colors.foreground}
format-padding = 1

; ---------------- Bluetooth Keyboard ----------------
[module/bluetooth-keyboard]
type = custom/script
exec = bluetoothctl devices Connected | grep -q 'AULA' && echo " "
exec-if = bluetoothctl devices Connected | grep -i 'AULA'
interval = 2
format-prefix = 
format-prefix-foreground = ${colors.foreground}
format-padding = 1

; ---------------- Mouse ----------------
[module/mouse]
type = custom/script
exec = ~/.config/polybar/scripts/mouse.sh
interval = 3
format-prefix = 󰚥
format-prefix-foreground = ${colors.foreground}
format-padding = 1

; ---------------- Webcam ----------------
[module/webcam]
type = custom/script
exec = ~/.config/polybar/scripts/webcam.sh
interval = 3
format-prefix = 󰚥
format-prefix-foreground = ${colors.foreground}
format-padding = 1

; ---------------- Keyboard ----------------
[module/keyboard]
type = custom/script
exec = ~/.config/polybar/scripts/keyboard.sh
interval = 3
format-prefix = 󰚥
format-prefix-foreground = ${colors.foreground}
format-padding = 1

; ---------------- Spotify ----------------
[module/spotify]
type = custom/script
tail = true
interval = 1
format-prefix = "  "
exec = ~/.config/polybar/scripts/scroll_spotify_status.sh

